// Global country list for employer signup
export const GLOBAL_COUNTRIES = [
  // Pacific Islands (for reference, but employers can be from anywhere)
  { value: 'Guam', label: 'Guam' },
  { value: 'CNMI', label: 'CNMI (Northern Mariana Islands)' },
  { value: 'Palau', label: 'Palau' },
  { value: 'Marshall Islands', label: 'Marshall Islands' },
  { value: 'FSM - Yap', label: 'FSM - Yap State' },
  { value: 'FSM - Chuuk', label: 'FSM - Chuuk State' },
  { value: 'FSM - Pohnpei', label: 'FSM - Pohnpei State' },
  { value: 'FSM - Kosrae', label: 'FSM - Kosrae State' },
  { value: 'Hawaii', label: 'Hawaii, USA' },
  
  // North America
  { value: 'United States', label: 'United States' },
  { value: 'Canada', label: 'Canada' },
  { value: 'Mexico', label: 'Mexico' },
  
  // Central America & Caribbean
  { value: 'Belize', label: 'Belize' },
  { value: 'Costa Rica', label: 'Costa Rica' },
  { value: 'El Salvador', label: 'El Salvador' },
  { value: 'Guatemala', label: 'Guatemala' },
  { value: 'Honduras', label: 'Honduras' },
  { value: 'Nicaragua', label: 'Nicaragua' },
  { value: 'Panama', label: 'Panama' },
  { value: 'Bahamas', label: 'Bahamas' },
  { value: 'Barbados', label: 'Barbados' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'Dominican Republic', label: 'Dominican Republic' },
  { value: 'Haiti', label: 'Haiti' },
  { value: 'Jamaica', label: 'Jamaica' },
  { value: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
  
  // South America
  { value: 'Argentina', label: 'Argentina' },
  { value: 'Bolivia', label: 'Bolivia' },
  { value: 'Brazil', label: 'Brazil' },
  { value: 'Chile', label: 'Chile' },
  { value: 'Colombia', label: 'Colombia' },
  { value: 'Ecuador', label: 'Ecuador' },
  { value: 'Guyana', label: 'Guyana' },
  { value: 'Paraguay', label: 'Paraguay' },
  { value: 'Peru', label: 'Peru' },
  { value: 'Suriname', label: 'Suriname' },
  { value: 'Uruguay', label: 'Uruguay' },
  { value: 'Venezuela', label: 'Venezuela' },
  
  // Europe
  { value: 'United Kingdom', label: 'United Kingdom' },
  { value: 'Germany', label: 'Germany' },
  { value: 'France', label: 'France' },
  { value: 'Spain', label: 'Spain' },
  { value: 'Italy', label: 'Italy' },
  { value: 'Netherlands', label: 'Netherlands' },
  { value: 'Belgium', label: 'Belgium' },
  { value: 'Switzerland', label: 'Switzerland' },
  { value: 'Austria', label: 'Austria' },
  { value: 'Sweden', label: 'Sweden' },
  { value: 'Norway', label: 'Norway' },
  { value: 'Denmark', label: 'Denmark' },
  { value: 'Finland', label: 'Finland' },
  { value: 'Ireland', label: 'Ireland' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'Greece', label: 'Greece' },
  { value: 'Poland', label: 'Poland' },
  { value: 'Czech Republic', label: 'Czech Republic' },
  { value: 'Hungary', label: 'Hungary' },
  { value: 'Romania', label: 'Romania' },
  { value: 'Bulgaria', label: 'Bulgaria' },
  { value: 'Croatia', label: 'Croatia' },
  { value: 'Serbia', label: 'Serbia' },
  { value: 'Slovakia', label: 'Slovakia' },
  { value: 'Slovenia', label: 'Slovenia' },
  { value: 'Estonia', label: 'Estonia' },
  { value: 'Latvia', label: 'Latvia' },
  { value: 'Lithuania', label: 'Lithuania' },
  { value: 'Iceland', label: 'Iceland' },
  { value: 'Luxembourg', label: 'Luxembourg' },
  { value: 'Malta', label: 'Malta' },
  { value: 'Cyprus', label: 'Cyprus' },
  
  // Asia
  { value: 'China', label: 'China' },
  { value: 'Japan', label: 'Japan' },
  { value: 'South Korea', label: 'South Korea' },
  { value: 'India', label: 'India' },
  { value: 'Indonesia', label: 'Indonesia' },
  { value: 'Thailand', label: 'Thailand' },
  { value: 'Vietnam', label: 'Vietnam' },
  { value: 'Philippines', label: 'Philippines' },
  { value: 'Malaysia', label: 'Malaysia' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'Taiwan', label: 'Taiwan' },
  { value: 'Hong Kong', label: 'Hong Kong' },
  { value: 'Pakistan', label: 'Pakistan' },
  { value: 'Bangladesh', label: 'Bangladesh' },
  { value: 'Myanmar', label: 'Myanmar' },
  { value: 'Cambodia', label: 'Cambodia' },
  { value: 'Laos', label: 'Laos' },
  { value: 'Sri Lanka', label: 'Sri Lanka' },
  { value: 'Nepal', label: 'Nepal' },
  { value: 'Mongolia', label: 'Mongolia' },
  { value: 'Brunei', label: 'Brunei' },
  { value: 'Maldives', label: 'Maldives' },
  
  // Middle East
  { value: 'United Arab Emirates', label: 'United Arab Emirates' },
  { value: 'Saudi Arabia', label: 'Saudi Arabia' },
  { value: 'Qatar', label: 'Qatar' },
  { value: 'Kuwait', label: 'Kuwait' },
  { value: 'Bahrain', label: 'Bahrain' },
  { value: 'Oman', label: 'Oman' },
  { value: 'Israel', label: 'Israel' },
  { value: 'Turkey', label: 'Turkey' },
  { value: 'Iran', label: 'Iran' },
  { value: 'Iraq', label: 'Iraq' },
  { value: 'Jordan', label: 'Jordan' },
  { value: 'Lebanon', label: 'Lebanon' },
  { value: 'Syria', label: 'Syria' },
  { value: 'Yemen', label: 'Yemen' },
  
  // Africa
  { value: 'South Africa', label: 'South Africa' },
  { value: 'Nigeria', label: 'Nigeria' },
  { value: 'Kenya', label: 'Kenya' },
  { value: 'Egypt', label: 'Egypt' },
  { value: 'Morocco', label: 'Morocco' },
  { value: 'Tunisia', label: 'Tunisia' },
  { value: 'Algeria', label: 'Algeria' },
  { value: 'Ghana', label: 'Ghana' },
  { value: 'Ethiopia', label: 'Ethiopia' },
  { value: 'Tanzania', label: 'Tanzania' },
  { value: 'Uganda', label: 'Uganda' },
  { value: 'Rwanda', label: 'Rwanda' },
  { value: 'Senegal', label: 'Senegal' },
  { value: 'Ivory Coast', label: 'Ivory Coast' },
  { value: 'Cameroon', label: 'Cameroon' },
  { value: 'Zimbabwe', label: 'Zimbabwe' },
  { value: 'Zambia', label: 'Zambia' },
  { value: 'Botswana', label: 'Botswana' },
  { value: 'Namibia', label: 'Namibia' },
  { value: 'Mauritius', label: 'Mauritius' },
  
  // Oceania
  { value: 'Australia', label: 'Australia' },
  { value: 'New Zealand', label: 'New Zealand' },
  { value: 'Fiji', label: 'Fiji' },
  { value: 'Papua New Guinea', label: 'Papua New Guinea' },
  { value: 'Samoa', label: 'Samoa' },
  { value: 'Tonga', label: 'Tonga' },
  { value: 'Vanuatu', label: 'Vanuatu' },
  { value: 'Solomon Islands', label: 'Solomon Islands' },
  { value: 'Kiribati', label: 'Kiribati' },
  { value: 'Tuvalu', label: 'Tuvalu' },
  { value: 'Nauru', label: 'Nauru' },
  
  // Other
  { value: 'Other', label: 'Other / Not Listed' },
];

// Pacific Islands locations for students and education institutions ONLY
export const PACIFIC_ISLAND_LOCATIONS = [
  { value: 'CNMI', label: 'CNMI (Commonwealth of the Northern Mariana Islands)' },
  { value: 'FSM - Yap', label: 'FSM - Yap State' },
  { value: 'FSM - Chuuk', label: 'FSM - Chuuk State' },
  { value: 'FSM - Pohnpei', label: 'FSM - Pohnpei State' },
  { value: 'FSM - Kosrae', label: 'FSM - Kosrae State' },
  { value: 'Guam', label: 'Guam' },
  { value: 'Hawaii', label: 'Hawaii' },
  { value: 'Palau', label: 'Palau' },
  { value: 'Marshall Islands', label: 'Marshall Islands' },
];
